modLoader="javafml"
loaderVersion="[39,)"
license="CC BY-NC-SA 3.0 Unported"
issueTrackerURL="https://github.com/Eltrut-Co/Lepton/issues"
[[mods]]
modId="lepton"
version="2.0.0"
displayName="Lepton"
logoFile="lepton.png"
credits="EltrutLikes"
authors="Eltrut & Co."
description='''
Smallest things.
'''

[[dependencies.lepton]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lepton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lepton]]
    modId="differentiate"
    mandatory=true
    versionRange="[1.0.2,)"
    ordering="AFTER"
    side="BOTH"